/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Presentador.IVistaPrincipal;
import Presentador.PresentadorPrincipal;

/**
 *
 * @author fermatmir
 */
public class VistaPrincipal extends javax.swing.JFrame implements IVistaPrincipal{
    private PresentadorPrincipal presentadorPrincipal;
    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCrearPaquete = new javax.swing.JButton();
        btnCrearSalida = new javax.swing.JButton();
        btnModificarEstado = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCrearPaquete.setText("Crear Paquete");
        btnCrearPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPaqueteActionPerformed(evt);
            }
        });

        btnCrearSalida.setText("Crear Salida");
        btnCrearSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearSalidaActionPerformed(evt);
            }
        });

        btnModificarEstado.setText("Modificar Estado");
        btnModificarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarEstadoActionPerformed(evt);
            }
        });

        jLabel1.setText("Operador Turistico");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnModificarEstado)
                    .addComponent(btnCrearPaquete)
                    .addComponent(btnCrearSalida))
                .addGap(0, 222, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(btnCrearPaquete)
                .addGap(32, 32, 32)
                .addComponent(btnCrearSalida)
                .addGap(35, 35, 35)
                .addComponent(btnModificarEstado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(btnSalir))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPaqueteActionPerformed
        this.getPresenter().runCrearPaquete();
    }//GEN-LAST:event_btnCrearPaqueteActionPerformed

    private void btnCrearSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearSalidaActionPerformed
       this.getPresenter().runCrearSalida();
    }//GEN-LAST:event_btnCrearSalidaActionPerformed

    private void btnModificarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarEstadoActionPerformed
       this.getPresenter().runModificarEstado();
    }//GEN-LAST:event_btnModificarEstadoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
      this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearPaquete;
    private javax.swing.JButton btnCrearSalida;
    private javax.swing.JButton btnModificarEstado;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public PresentadorPrincipal getPresenter() {
        return presentadorPrincipal;
    }

    @Override
    public void setPresenter(PresentadorPrincipal presentadorPrincipal) {
        this.presentadorPrincipal = presentadorPrincipal;
    }

    @Override
    public void updateModelFromView() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void updateViewFromModel() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void open() {
        setVisible(true);
    }

    @Override
    public void close() {
        dispose();
    }
}
